FROM ARG_FROM

MAINTAINER Thingful <info@thingful.net>

RUN wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | apt-key add - && \
    echo "deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main" >> /etc/apt/sources.list.d/pgdg.list && \
    apt-get update && \
    apt-get install  -y \
      build-essential \
      git \
      postgresql-client \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* 

RUN groupadd -f -g ARG_GID iotpilot && \
    useradd --shell /bin/bash -u ARG_UID -g ARG_GID iotpilot

# move retool out of /go/bin so binary is not masked
RUN go get -u github.com/twitchtv/retool && \
  cp /go/bin/* /usr/local/bin

WORKDIR ARG_WORKDIR

CMD ["/bin/sh"]
