# This file should not be used as is - instead should be used via Make which
# rewrites the below to match the current build environment.

version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ARG_DOCKERFILE
    image: ARG_IMAGE
    volumes:
      - ARG_PWD/.go:/go
      - ARG_PWD:/go/src/ARG_PKG
      - ARG_PWD/bin/ARG_ARCH:/go/bin
      - ARG_PWD/.go/std:/usr/local/go/pkg/linux_ARG_ARCH_static
      - ARG_PWD/.cache/go-build:/.cache/go-build
    working_dir: /go/src/ARG_PKG
    ports:
      - "8080:8080"
    command: [ "/go/src/ARG_PKG/build/run.sh", "/go/bin/ARG_BIN", "server" ]
    depends_on:
      - postgres
    environment:
      - PGHOST=postgres
      - PGPASSWORD=password
      - PGUSER=iotenc
      - IOTENCODER_DATABASE_URL=postgres://iotenc:password@postgres:5432/iotenc_development?sslmode=disable
      - IOTENCODER_ENCRYPTION_PASSWORD=e3d741d6f84afc301d8e32c66e51f264


  postgres:
    image: postgres:10-alpine
    ports:
      - "5432"
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=iotenc
      - POSTGRES_DB=postgres

volumes:
  postgres_vol:
