FROM ARG_FROM

MAINTAINER Thingful <info@thingful.net>

RUN apt-get update &&  apt-get install  -y \
    build-essential \
    git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# move retool out of /go/bin so binary is not masked
RUN go get -u github.com/twitchtv/retool && \
  cp /go/bin/* /usr/local/bin

WORKDIR ARG_WORKDIR

CMD ["/bin/sh"]
